#include "GLee.h"
#include "CorePluginsIncludes.h"

#include "SamplePlugin.h"
#include "SamplePlugin2.h"
#include "Kinect.h"
#include "Wave.h"
#include "FysiskeReaktioner.h"
#include "TrackingElements.h"
#include "Leaking.h"
#include "Umbilical.h"
#include "Ocean.h"
#include "VideoPlayer.h"
#include "Statestik.h"
#include "Beach.h"
#include "Voice.h"

#include "SceneX.h"
//#include "Tracking.h"